### ISSUE TITLE
Authentication over MQTT

### ISSUE THREAD

**Issue by kamranIoTDeveloper** [beaver71/Mobius#2]
Authentication working fine over REST API, How to define authentication header in nCube to connect it with Mobius over MQTT

**Comment by beaver71** [comment]
We adopted a sort of Basic Authentication via topic also for MQTT; see my comment here https://github.com/IoTKETI/Mobius/pull/8#issuecomment-334144512

**Comment by kamranIoTDeveloper** [comment]
@beaver71 thanks, issue resolved.
